### ISSUE TITLE
An error occurs in purpur 1.20.4

### ISSUE THREAD

**Issue by excaliburkim** [s5y-ux/MoreBosses#1]
/version
   Current: git-Purpur-2176 (MC: 1.20.4)*
   Previous: git-Purpur-2175 (MC: 1.20.4)
   You are running the latest version

**I really want to try it! Thank you.**

[06:01:56 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'MoreBossesV2.0.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.21
        at org.bukkit.craftbukkit.v1_20_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:389) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:119) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:521) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by s5y-ux** [comment]
I've updated the release, try deleting the file from your plugins folder and reinstalling it

**Comment by s5y-ux** [comment]
> /version Current: git-Purpur-2176 (MC: 1.20.4)* Previous: git-Purpur-2175 (MC: 1.20.4) You are running the latest version
> 
> **I really want to try it! Thank you.**
> 
> [06:01:56 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'MoreBossesV2.0.1.jar' in folder 'plugins' org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.21 at org.bukkit.craftbukkit.v1_20_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:389) ~[purpur-1.20.4.jar:git-Purpur-2176] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:119) ~[purpur-1.20.4.jar:git-Purpur-2176] at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.20.4.jar:git-Purpur-2176] at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.4.jar:git-Purpur-2176] at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.20.4.jar:git-Purpur-2176] at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.4.jar:git-Purpur-2176] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:521) ~[purpur-1.20.4.jar:git-Purpur-2176] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[purpur-1.20.4.jar:git-Purpur-2176] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176] at java.lang.Thread.run(Thread.java:1570) ~[?:?]


I've updated the release, try deleting the file from your plugins folder and reinstalling it

**Comment by excaliburkim** [comment]
Thank you for the correction. I will use it well. Be happy.
